// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFS3_0o7HNOKe80XoU0DvB9jwyaq4Bk4',
    appId: '1:851787566023:web:25c25177a90255de75a7e2',
    messagingSenderId: '851787566023',
    projectId: 'learnloop-a027c',
    authDomain: 'learnloop-a027c.firebaseapp.com',
    storageBucket: 'learnloop-a027c.firebasestorage.app',
    measurementId: 'G-VNZLBYP0DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS793PG1dj5lLPVBILIStNYveJdX_cAuU',
    appId: '1:851787566023:android:182d994ee8816caa75a7e2',
    messagingSenderId: '851787566023',
    projectId: 'learnloop-a027c',
    storageBucket: 'learnloop-a027c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRGzpkov7DCjR7wxQOjiodyg65Wlaj7M',
    appId: '1:851787566023:ios:fd1840a05b23912675a7e2',
    messagingSenderId: '851787566023',
    projectId: 'learnloop-a027c',
    storageBucket: 'learnloop-a027c.firebasestorage.app',
    iosBundleId: 'com.example.learnloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRGzpkov7DCjR7wxQOjiodyg65Wlaj7M',
    appId: '1:851787566023:ios:fd1840a05b23912675a7e2',
    messagingSenderId: '851787566023',
    projectId: 'learnloop-a027c',
    storageBucket: 'learnloop-a027c.firebasestorage.app',
    iosBundleId: 'com.example.learnloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFS3_0o7HNOKe80XoU0DvB9jwyaq4Bk4',
    appId: '1:851787566023:web:ffe41d258565393e75a7e2',
    messagingSenderId: '851787566023',
    projectId: 'learnloop-a027c',
    authDomain: 'learnloop-a027c.firebaseapp.com',
    storageBucket: 'learnloop-a027c.firebasestorage.app',
    measurementId: 'G-DQDF3B0SHX',
  );
}
